version: '3'

services:
  productinfo:
    environment:
     - NODE_ENV=production
     - PORT=3003
    image: richard009/hackreactor2019
    depends_on:
     - 'database'
    ports:
     - '3003:3003'

  database:
    image: mysql:5.7
    environment:
     MYSQL_ROOT_PASSWORD: kqed
    command: --default-authentication-plugin=mysql_native_password